### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by nmquaan** [vkarpov15/run-rs#2]
When I run the package with command run-rs --version 4.0.0 occur error 
`ReferenceError: type is not defined
    at getOS (C:\Users\PC\AppData\Roaming\nvm\v8.9.4\node_modules\run-rs\dl.js:27:49)
    at dl (C:\Users\PC\AppData\Roaming\nvm\v8.9.4\node_modules\run-rs\dl.js:6:14)
    at run (C:\Users\PC\AppData\Roaming\nvm\v8.9.4\node_modules\run-rs\index.js:38:5)
    at run.next (<anonymous>)
    at onFulfilled (C:\Users\PC\AppData\Roaming\nvm\v8.9.4\node_modules\run-rs\node_modules\co\index.js:65:19)
    at C:\Users\PC\AppData\Roaming\nvm\v8.9.4\node_modules\run-rs\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (C:\Users\PC\AppData\Roaming\nvm\v8.9.4\node_modules\run-rs\node_modules\co\index.js:50:10)
    at Object.<anonymous> (C:\Users\PC\AppData\Roaming\nvm\v8.9.4\node_modules\run-rs\index.js:23:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)`
Please help me resolve this issue
Thanks for the support!

**Comment by aoi-umi** [comment]
@nmquaan 
OS Support

Run-rs supports Linux and OSX. Windows is not currently supported.

**Comment by aoi-umi** [comment]
centos7
 run-rs -v 4.0.0 --shell

Purging database...
Running '/usr/local/src/node-v8.0.0-linux-x64/lib/node_modules/run-rs/4.0.0/mongod'
Starting replica set...
Error: failed to start mongod with options --port=27017,--dbpath=/home/yiguain/data/27017,--bind_ip=localhost,--replSet=rs
    at ChildProcess.<anonymous> (/usr/local/src/node-v8.0.0-linux-x64/lib/node_modules/run-rs/node_modules/mongodb-topology-manager/lib/server.js:375:27)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)

**Comment by vkarpov15** [comment]
Thanks for reporting, we [only support OSX and Linux currently](https://github.com/vkarpov15/run-rs#os-support) but we'll keep this issue open to track windows support.
