### ISSUE TITLE
error when running run-rs when another mongo is running

### ISSUE THREAD

**Issue by sibelius** [vkarpov15/run-rs#21]
I'm using Mac OS X

I've tried to use run-rs with the following command

```jsx
run-rs -v 4.0.5 --shell -p 28017
```

and I got the following crash, I have another mongo running already

```jsx
2019-01-25T16:18:17.179-0200 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2019-01-25T16:18:17.189-0200 I CONTROL  [initandlisten] MongoDB starting : pid=68440 port=28017 dbpath=/Users/sibelius/Dev/app/./data/28017 64-bit host=sibelius-pro
2019-01-25T16:18:17.190-0200 I CONTROL  [initandlisten] db version v4.0.5
2019-01-25T16:18:17.190-0200 I CONTROL  [initandlisten] git version: 3739429dd92b92d1b0ab120911a23d50bf03c412
2019-01-25T16:18:17.190-0200 I CONTROL  [initandlisten] allocator: system
2019-01-25T16:18:17.190-0200 I CONTROL  [initandlisten] modules: none
2019-01-25T16:18:17.190-0200 I CONTROL  [initandlisten] build environment:
2019-01-25T16:18:17.190-0200 I CONTROL  [initandlisten]     distarch: x86_64
2019-01-25T16:18:17.190-0200 I CONTROL  [initandlisten]     target_arch: x86_64
2019-01-25T16:18:17.190-0200 I CONTROL  [initandlisten] options: { net: { bindIp: "localhost", port: 28017 }, replication: { replSet: "rs" }, storage: { dbPath: "/Users/sibelius/Dev/app/./data/28017" } }
2019-01-25T16:18:17.192-0200 E STORAGE  [initandlisten] Failed to set up listener: SocketException: Can't assign requested address
2019-01-25T16:18:17.193-0200 I CONTROL  [initandlisten] now exiting
2019-01-25T16:18:17.193-0200 I CONTROL  [initandlisten] shutting down with code:48

    at ChildProcess.<anonymous> (/Users/sibelius/.nvm/versions/node/v10.12.0/lib/node_modules/run-rs/node_modules/mongodb-topology-manager/lib/server.js:404:15)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

**Comment by vkarpov15** [comment]
Hmm I suppose we can make this error more readable, but I don't think killing other running mongodb processed is something this tool should do

**Comment by sibelius** [comment]
Can we run both in parallel?

**Comment by vkarpov15** [comment]
Not on the same port. You'll have to use the -p option to run-rs to override the default port
