### ISSUE TITLE
Unreadable error if --mongod path not found

### ISSUE THREAD

**Issue by coommark** [vkarpov15/run-rs#25]
I installed this. I also have Mongo 4.0.6 installed. When I run `run-rs --mongod` it fails with this message:

```
C:\Users\user\AppData\Roaming\npm\node_modules\run-rs\node_modules\mongodb-topology-manager\lib\replset.js:124
            .toString()
             ^

TypeError: Cannot read property 'toString' of null
    at ChildProcess.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\run-rs\node_modules\mongodb-topology-manager\lib\replset.js:124:14)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
```

So I commented out the `proc.on('close', function()` to see, but when I run, it still fails with:

```
$ run-rs --mongod
Purging database...
Running 'mongod' [ 27017, 27018, 27019 ]
Starting replica set...
Error: spawn mongod ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

Please is there any pointers how to make this work? I just want to try out transactions in NodeJS Mongoose.

**Comment by coommark** [comment]
Got it. I had to navigate to the bin folder of MongoDB as administrator before it worked.

**Comment by vkarpov15** [comment]
Why are you running it with `--mongod`? That option is only if you want to specify the path of the mongod executable to run.

**Comment by coommark** [comment]
Yes I already have MongoDB installed. I don't want to download a new mongo. 

I just cd into the installed Mongo bin directory and run the command with admin privileges. It's working as expected.

Thanks for awesome work you doing.

**Comment by vkarpov15** [comment]
Thanks, glad it works for you. You can also pass the path of the mongod you want to use, like `run-rs --mongod /c/path/to/mongod`

Will improve this error message :+1:
