### ISSUE TITLE
Not able to start run-rs

### ISSUE THREAD

**Issue by thiagoprz** [vkarpov15/run-rs#27]
Hi, i'm trying to use run-rs on a project but i'm having the following issue:

$ sudo run-rs -v 4.0.0        
Purging database...
Running '/usr/local/lib/node_modules/run-rs/4.0.0/mongod' [ 27017, 27018, 27019 ]
Starting replica set...
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connection 0 to localhost:27017 timed out]
    at Pool.<anonymous> (/usr/local/lib/node_modules/run-rs/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/usr/local/lib/node_modules/run-rs/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/usr/local/lib/node_modules/run-rs/node_modules/mongodb-core/lib/connection/connection.js:257:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

My setup is Linux Mint 19 (Ubuntu 18.04 LTS)

**Comment by thiagoprz** [comment]
Apparently it was the version of my node. Just updated and worked again
