### ISSUE TITLE
ubuntu 16.04 LTS install failed

### ISSUE THREAD

**Issue by dtboy1995** [vkarpov15/run-rs#29]
### global install
> sudo npm i run-rs -g

```log
/usr/local/bin/run-rs -> /usr/local/lib/node_modules/run-rs/index.js

> kerberos@1.1.2 install /usr/local/lib/node_modules/run-rs/node_modules/kerberos
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.6.0 runtime=node arch=x64 libc= platform=linux)
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/run-rs/node_modules/kerberos/build'
gyp ERR! System Linux 4.15.0-46-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/run-rs/node_modules/kerberos
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kerberos@1.1.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kerberos@1.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dtboy/.npm/_logs/2019-03-28T01_19_53_661Z-debug.log
```
### install 
> npm i run-rs
```
kerberos@1.1.2 install /home/dtboy/node_modules/kerberos
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.6.0 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/home/dtboy/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/src/kerberos.o
In file included from ../src/kerberos_common.h:7:0,
                 from ../src/kerberos.h:5,
                 from ../src/kerberos.cc:1:
../src/unix/kerberos_gss.h:18:31: fatal error: gssapi/gssapi.h: 没有那个文件或目录
compilation terminated.
kerberos.target.mk:104: recipe for target 'Release/obj.target/kerberos/src/kerberos.o' failed
make: *** [Release/obj.target/kerberos/src/kerberos.o] Error 1
make: Leaving directory '/home/dtboy/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.15.0-46-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dtboy/node_modules/kerberos
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/dtboy/package.json'
npm WARN dtboy No description
npm WARN dtboy No repository field.
npm WARN dtboy No README data
npm WARN dtboy No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kerberos@1.1.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kerberos@1.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dtboy/.npm/_logs/2019-03-28T01_20_48_156Z-debug.log
```

**Comment by vkarpov15** [comment]
Does running `run-rs` fail after this message? This error is from an auth module the mongodb driver depends on and the driver should install successfully even if kerberos installation fails

**Comment by dtboy1995** [comment]
@vkarpov15  thanks
- global install
```
$ run-rs
run-rs: command not found 
```
- local install
i can use npx
```
npx run-rs -v 4.0.0
In file included from ../src/kerberos_common.h:7:0,
                 from ../src/kerberos.h:5,
                 from ../src/kerberos.cc:1:
../src/unix/kerberos_gss.h:18:31: fatal error: gssapi/gssapi.h: 没有那个文件或目录
compilation terminated.
make: *** [Release/obj.target/kerberos/src/kerberos.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.15.0-46-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dtboy/.npm/_npx/3943/lib/node_modules/run-rs/node_modules/kerberos
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kerberos@1.1.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kerberos@1.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dtboy/.npm/_logs/2019-03-29T01_24_13_577Z-debug.log
安装 run-rs@latest 失败，错误代码：1
```

**Comment by dtboy1995** [comment]
```
$ uname -a
Linux ubuntu-dev 4.15.0-46-generic #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
```
$node -v
v11.6.0
npm -v
6.9.0
```

**Comment by andreialecu** [comment]
Same issue here:

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

```
npm install run-rs -g
/home/aandrei/.nvm/versions/node/v11.10.0/bin/run-rs -> /home/aandrei/.nvm/versions/node/v11.10.0/lib/node_modules/run-rs/index.js

> kerberos@1.1.2 install /home/aandrei/.nvm/versions/node/v11.10.0/lib/node_modules/run-rs/node_modules/kerberos
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.10.0 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/home/aandrei/.nvm/versions/node/v11.10.0/lib/node_modules/run-rs/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/src/kerberos.o
In file included from ../src/kerberos_common.h:7:0,
                 from ../src/kerberos.h:5,
                 from ../src/kerberos.cc:1:
../src/unix/kerberos_gss.h:18:31: fatal error: gssapi/gssapi.h: No such file or directory
compilation terminated.
kerberos.target.mk:104: recipe for target 'Release/obj.target/kerberos/src/kerberos.o' failed
make: *** [Release/obj.target/kerberos/src/kerberos.o] Error 1
make: Leaving directory '/home/aandrei/.nvm/versions/node/v11.10.0/lib/node_modules/run-rs/node_modules/kerberos/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/aandrei/.nvm/versions/node/v11.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.4.0-17763-Microsoft
gyp ERR! command "/home/aandrei/.nvm/versions/node/v11.10.0/bin/node" "/home/aandrei/.nvm/versions/node/v11.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/aandrei/.nvm/versions/node/v11.10.0/lib/node_modules/run-rs/node_modules/kerberos
gyp ERR! node -v v11.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kerberos@1.1.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kerberos@1.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aandrei/.npm/_logs/2019-04-01T11_04_34_824Z-debug.log
```

**Comment by andreialecu** [comment]
Fixed with `sudo apt-get install libkrb5-dev`, you might want to add it to the README.

**Comment by dtboy1995** [comment]
@andreialecu thanks I'll try.

**Comment by jnosornov** [comment]
It also happened to me, what I did downgrade the node version to 10, and it worked. Have not tried the @andreialecu solution yet.
