### ISSUE TITLE
Cannot use version 4.2.0

### ISSUE THREAD

**Issue by mexin** [vkarpov15/run-rs#35]
I was trying to use latest version 4.2.0 but when I run `run-rs -v 4.2.0` I get the following output error
```
Downloading MongoDB 4.2.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:100   243    0   243    0     0   1265      0 --:--:-- --:--:-- --:--:--  1265

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: Command failed: tar -zxvf mongodb-linux-x86_64-4.2.0.tgz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at dl (/home/luismexin/.nvm/versions/node/v10.15.3/lib/node_modules/run-rs/dl.js:51:5)
    at run (/home/luismexin/.nvm/versions/node/v10.15.3/lib/node_modules/run-rs/index.js:80:7)
    at run.next (<anonymous>)
    at onFulfilled (/home/luismexin/.nvm/versions/node/v10.15.3/lib/node_modules/run-rs/node_modules/co/index.js:65:19)
    at /home/luismexin/.nvm/versions/node/v10.15.3/lib/node_modules/run-rs/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/home/luismexin/.nvm/versions/node/v10.15.3/lib/node_modules/run-rs/node_modules/co/index.js:50:10)
    at Object.<anonymous> (/home/luismexin/.nvm/versions/node/v10.15.3/lib/node_modules/run-rs/index.js:31:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)

```
OS: Ubuntu 19.04
Node version 10.15.3

**Comment by vkarpov15** [comment]
Should be fixed in 0.6.0 with #40
