### ISSUE TITLE
TypeError: Cannot read property 'includes' of undefined when upgraded from 0.6.2 to 0.7.0

### ISSUE THREAD

**Issue by mexin** [vkarpov15/run-rs#46]
Getting the following error when I upgraded the package to 0.7.0

```
TypeError: Cannot read property 'includes' of undefined
    at /home/luismexin/.nvm/versions/node/v12.14.1/lib/node_modules/run-rs/index.js:211:23
    at Generator.throw (<anonymous>)
    at onRejected (/home/luismexin/.nvm/versions/node/v12.14.1/lib/node_modules/run-rs/node_modules/co/index.js:81:24)
    at tryCatcher (/home/luismexin/.nvm/versions/node/v12.14.1/lib/node_modules/run-rs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/luismexin/.nvm/versions/node/v12.14.1/lib/node_modules/run-rs/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/luismexin/.nvm/versions/node/v12.14.1/lib/node_modules/run-rs/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/luismexin/.nvm/versions/node/v12.14.1/lib/node_modules/run-rs/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/luismexin/.nvm/versions/node/v12.14.1/lib/node_modules/run-rs/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/luismexin/.nvm/versions/node/v12.14.1/lib/node_modules/run-rs/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/luismexin/.nvm/versions/node/v12.14.1/lib/node_modules/run-rs/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/luismexin/.nvm/versions/node/v12.14.1/lib/node_modules/run-rs/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/home/luismexin/.nvm/versions/node/v12.14.1/lib/node_modules/run-rs/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)

```

**Comment by sreevisakh** [comment]
https://github.com/vkarpov15/run-rs/blob/1a217d028352c84f41eda7928597d2f89fda1d31/index.js#L211

here `err` is an array. so `err.message` is undefined

**Comment by ucejtech** [comment]
Is this being worked on or can I create a pull request?
