### ISSUE TITLE
Starting rs with --keep throws an error

### ISSUE THREAD

**Issue by ranka23** [vkarpov15/run-rs#61]
Hey. Great package. Makes life easier. 

Right now I've been facing an issue:
`run-rs --keep` throws an error. Not quite sure what's happening. The error messages are a little difficult to follow and I'm no MongoDb expert.

I'm using the latest version of run-rs.

Also, `run-rs` works fine and so does `run-rs --mongod`

```
:~$ run-rs --keep
Skipping purge
Running '/usr/local/lib/node_modules/run-rs/4.0.12/mongod' [ 27017, 27018, 27019 ]
Restarting replica set...
(node:12679) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12679) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:12679) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:12679) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
Error: failed to start mongod with options [
  '--port=27017',
  '--dbpath=/home/user/data/27017',
  '--bind_ip=localhost',
  '--replSet=rs'
]
2021-06-20T22:23:40.781+0530 I STORAGE  [main] Max cache overflow file size custom option: 0
2021-06-20T22:23:40.783+0530 I CONTROL  [initandlisten] MongoDB starting : pid=12687 port=27017 dbpath=/home/user/data/27017 64-bit host=user
2021-06-20T22:23:40.783+0530 I CONTROL  [initandlisten] db version v4.0.12
2021-06-20T22:23:40.783+0530 I CONTROL  [initandlisten] git version: 5776e3cbf9e7afe86e6b29e22520ffb6766e95d4
2021-06-20T22:23:40.783+0530 I CONTROL  [initandlisten] allocator: tcmalloc
2021-06-20T22:23:40.783+0530 I CONTROL  [initandlisten] modules: none
2021-06-20T22:23:40.784+0530 I CONTROL  [initandlisten] build environment:
2021-06-20T22:23:40.784+0530 I CONTROL  [initandlisten]     distarch: x86_64
2021-06-20T22:23:40.784+0530 I CONTROL  [initandlisten]     target_arch: x86_64
2021-06-20T22:23:40.784+0530 I CONTROL  [initandlisten] options: { net: { bindIp: "localhost", port: 27017 }, replication: { replSet: "rs" }, storage: { dbPath: "/home/user/data/27017" } }
2021-06-20T22:23:40.784+0530 I STORAGE  [initandlisten] Detected data files in /home/user/data/27017 created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2021-06-20T22:23:40.784+0530 I STORAGE  [initandlisten] 
2021-06-20T22:23:40.784+0530 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2021-06-20T22:23:40.784+0530 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2021-06-20T22:23:40.784+0530 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7390M,cache_overflow=(file_max=0M),session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2021-06-20T22:23:41.152+0530 E STORAGE  [initandlisten] WiredTiger error (-31802) [1624208021:152541][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 606: unable to read root page from file:WiredTiger.wt: WT_ERROR: non-specific WiredTiger error Raw: [1624208021:152541][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 606: unable to read root page from file:WiredTiger.wt: WT_ERROR: non-specific WiredTiger error
2021-06-20T22:23:41.152+0530 E STORAGE  [initandlisten] WiredTiger error (0) [1624208021:152592][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 613: WiredTiger has failed to open its metadata Raw: [1624208021:152592][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 613: WiredTiger has failed to open its metadata
2021-06-20T22:23:41.152+0530 E STORAGE  [initandlisten] WiredTiger error (0) [1624208021:152598][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 616: This may be due to the database files being encrypted, being from an older version or due to corruption on disk Raw: [1624208021:152598][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 616: This may be due to the database files being encrypted, being from an older version or due to corruption on disk
2021-06-20T22:23:41.152+0530 E STORAGE  [initandlisten] WiredTiger error (0) [1624208021:152604][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 619: You should confirm that you have opened the database with the correct options including all encryption and compression options Raw: [1624208021:152604][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 619: You should confirm that you have opened the database with the correct options including all encryption and compression options
2021-06-20T22:23:41.154+0530 E STORAGE  [initandlisten] WiredTiger error (-31802) [1624208021:154925][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 606: unable to read root page from file:WiredTiger.wt: WT_ERROR: non-specific WiredTiger error Raw: [1624208021:154925][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 606: unable to read root page from file:WiredTiger.wt: WT_ERROR: non-specific WiredTiger error
2021-06-20T22:23:41.154+0530 E STORAGE  [initandlisten] WiredTiger error (0) [1624208021:154975][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 613: WiredTiger has failed to open its metadata Raw: [1624208021:154975][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 613: WiredTiger has failed to open its metadata
2021-06-20T22:23:41.154+0530 E STORAGE  [initandlisten] WiredTiger error (0) [1624208021:154980][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 616: This may be due to the database files being encrypted, being from an older version or due to corruption on disk Raw: [1624208021:154980][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 616: This may be due to the database files being encrypted, being from an older version or due to corruption on disk
2021-06-20T22:23:41.154+0530 E STORAGE  [initandlisten] WiredTiger error (0) [1624208021:154985][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 619: You should confirm that you have opened the database with the correct options including all encryption and compression options Raw: [1624208021:154985][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 619: You should confirm that you have opened the database with the correct options including all encryption and compression options
2021-06-20T22:23:41.157+0530 E STORAGE  [initandlisten] WiredTiger error (-31802) [1624208021:157318][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 606: unable to read root page from file:WiredTiger.wt: WT_ERROR: non-specific WiredTiger error Raw: [1624208021:157318][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 606: unable to read root page from file:WiredTiger.wt: WT_ERROR: non-specific WiredTiger error
2021-06-20T22:23:41.157+0530 E STORAGE  [initandlisten] WiredTiger error (0) [1624208021:157369][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 613: WiredTiger has failed to open its metadata Raw: [1624208021:157369][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 613: WiredTiger has failed to open its metadata
2021-06-20T22:23:41.157+0530 E STORAGE  [initandlisten] WiredTiger error (0) [1624208021:157375][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 616: This may be due to the database files being encrypted, being from an older version or due to corruption on disk Raw: [1624208021:157375][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 616: This may be due to the database files being encrypted, being from an older version or due to corruption on disk
2021-06-20T22:23:41.157+0530 E STORAGE  [initandlisten] WiredTiger error (0) [1624208021:157379][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 619: You should confirm that you have opened the database with the correct options including all encryption and compression options Raw: [1624208021:157379][12687:0x7fc9cbe6ea40], file:WiredTiger.wt, connection: __wt_btree_tree_open, 619: You should confirm that you have opened the database with the correct options including all encryption and compression options
2021-06-20T22:23:41.158+0530 W STORAGE  [initandlisten] Failed to start up WiredTiger under any compatibility version.
2021-06-20T22:23:41.158+0530 W STORAGE  [initandlisten] WiredTiger metadata corruption detected
2021-06-20T22:23:41.158+0530 F STORAGE  [initandlisten] Please read the documentation for starting MongoDB with --repair here: http://dochub.mongodb.org/core/repair
2021-06-20T22:23:41.158+0530 F -        [initandlisten] Fatal Assertion 50944 at src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp 700
2021-06-20T22:23:41.158+0530 F -        [initandlisten] 

***aborting after fassert() failure



    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/run-rs/src/topologyManagerPatch.js:152:13)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

**Comment by vorticalbox** [comment]
I just solved this issue, turns out it was folder permissions  I have my mongo folder in `~/mongo` and ran `chmod 777 ~/mongo`
