### ISSUE TITLE
Error: Server is unavailable

### ISSUE THREAD

**Issue by zivlakmilos** [vkarpov15/run-rs#62]
I am getting error while try to start run-rs. When I check data folder, folder 27017 contain some files, but 27018 and 27019 are empty. MongoDB is running at 27017, but it looks like that it wont start servers at 27018 and 27019.

OS: archlinux 5.10.83-1-lts
Node:  v17.1.0.
npm: 8.1.3

`
Purging database...
Running '/usr/lib/node_modules/run-rs/4.0.12/mongod' [ 27017, 27018, 27019 ]
Starting replica set...
Error: Server is unavailable
    at /usr/lib/node_modules/run-rs/node_modules/mongodb-topology-manager/lib/utils.js:79:40
    at Socket.<anonymous> (/usr/lib/node_modules/run-rs/node_modules/mongodb-topology-manager/lib/utils.js:43:5)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
`

**Comment by MrFabio** [comment]
Same issue here, with node `v17.5.0`

**Comment by alextouzel** [comment]
Same here. Downgraded node to v15 and it worked.

**Comment by jmontroy90** [comment]
Same issue on `v18.0.0`, @vkarpov15 what do you think?

**Comment by jineshdoshi** [comment]
You probably already tried but switch to node 16 works.

**Comment by jineshdoshi** [comment]
I created a docker image to run mongodb 5.0.9 with run-rs
https://github.com/giant-connect/docker-mongodb-rs

**Comment by BigFax** [comment]
I have the same error on node v19.6.0.
27018 and 27019 are empty and can't start replica set.

```
Purging database...
Running 'mongod' [ 27017, 27018, 27019 ]
Starting replica set...
Error: Server is unavailable
```

**Comment by Lokkii** [comment]
It's possible that your environment or system settings do not support IPv6 or are not configured to work with "::1" - the IPv6 loopback address. Therefore, explicitly specifying **-h 127.0.0.1** allows for successful connection to the MongoDB server using only IPv4.
So, it should work:
`run-rs -h 127.0.0.1 [-m]`
