### ISSUE TITLE
Error: spawn Unknown system error -86

### ISSUE THREAD

**Issue by Sasha-hk** [vkarpov15/run-rs#71]
Runs on: MacBook Air M1 
OS: MacOS Monterey 12.4

Error:

```sh
➜ npx run-rs
Purging database...
Running '/Users/oleksandr/.nvm/versions/node/v16.15.1/lib/node_modules/run-rs/4.0.12/mongod' [ 27017, 27018, 27019 ]
Starting replica set...
Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:700:9)
    at /Users/oleksandr/.nvm/versions/node/v16.15.1/lib/node_modules/run-rs/node_modules/mongodb-topology-manager/lib/replset.js:94:18
    at Promise._execute (/Users/oleksandr/.nvm/versions/node/v16.15.1/lib/node_modules/run-rs/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/Users/oleksandr/.nvm/versions/node/v16.15.1/lib/node_modules/run-rs/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/Users/oleksandr/.nvm/versions/node/v16.15.1/lib/node_modules/run-rs/node_modules/bluebird/js/release/promise.js:103:10)
    at ReplSet.discover (/Users/oleksandr/.nvm/versions/node/v16.15.1/lib/node_modules/run-rs/node_modules/mongodb-topology-manager/lib/replset.js:93:12)
    at /Users/oleksandr/.nvm/versions/node/v16.15.1/lib/node_modules/run-rs/node_modules/mongodb-topology-manager/lib/replset.js:159:33
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/oleksandr/.nvm/versions/node/v16.15.1/lib/node_modules/run-rs/node_modules/co/index.js:65:19)
    at /Users/oleksandr/.nvm/versions/node/v16.15.1/lib/node_modules/run-rs/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/Users/oleksandr/.nvm/versions/node/v16.15.1/lib/node_modules/run-rs/node_modules/co/index.js:50:10)
    at /Users/oleksandr/.nvm/versions/node/v16.15.1/lib/node_modules/run-rs/node_modules/mongodb-topology-manager/lib/replset.js:146:7
    at Promise._execute (/Users/oleksandr/.nvm/versions/node/v16.15.1/lib/node_modules/run-rs/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/Users/oleksandr/.nvm/versions/node/v16.15.1/lib/node_modules/run-rs/node_modules/bluebird/js/release/promise.js:518:18)

```

**Comment by jorisderuiter** [comment]
Hi @Sasha-hk, I've been struggling with this issue for hours. Installing Rosetta did the trick!

**Comment by oleksandr-petryk** [comment]
@jorisderuiter  just tried it, everything works fine for me
