### ISSUE TITLE
Not Working with Node Version 18

### ISSUE THREAD

**Issue by baharalidurrani** [vkarpov15/run-rs#74]
### Hardware Info
Intel-Based MacBook Pro

### Software Info
Operating System: macOS Monterey Version `12.4 (21F79)`
`run-rs` Version: `0.7.7`

### Logs

```sh
❯ node --version
v18.7.0
❯ npm --version
8.15.0
❯ npx --version
8.15.0

❯ npm run start-local-db
> run-rs --keep -v 4.4.15

Skipping purge
Running '/Users/pro/workspace/hlp/hlp-mvp-nodejs-api/node_modules/run-rs/4.4.15/mongod' [ 27017, 27018, 27019 ]
Restarting replica set...
Error: Server is unavailable
    at /Users/pro/workspace/hlp/hlp-mvp-nodejs-api/node_modules/mongodb-topology-manager/lib/utils.js:79:40
    at Socket.<anonymous> (/Users/pro/workspace/hlp/hlp-mvp-nodejs-api/node_modules/mongodb-topology-manager/lib/utils.js:43:5)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
^C
```

Similar Issue #62

**Comment by anatoo** [comment]
I encountered the same problem but found a workaround. 
From v17 of Node.js, the `dns.lookup()` function resolves localhost to IPv6 `::1` instead of `127.0.0.1` in some cases.  It seems to work if you specify `--host="127.0.0.1"` in the options and specify IP directly instead of localhost on the mongo client side.

`$ npx run-rs --host=127.0.0.1`
