### ISSUE TITLE
mongoerror in windows powershell

### ISSUE THREAD

**Issue by XHMM** [vkarpov15/run-rs#8]
my `run-rs` version is `0.2.1` , when I run `run-rs -v 4.0.0` ,and get the following error：
did I  miss some additional configs ?
```
Purging database...
Running 'C:\Users\super\AppData\Roaming\npm\node_modules\run-rs/4.0.0/mongod.exe'
Starting replica set...
MongoError: This node was not started with the replSet option
    at Function.MongoError.create (C:\Users\super\AppData\Roaming\npm\node_modules\run-rs\node_modules\mongodb-topology-manager\node_modules\mongodb-core\lib\error.js:31:11)
    at C:\Users\super\AppData\Roaming\npm\node_modules\run-rs\node_modules\mongodb-topology-manager\node_modules\mongodb-core\lib\connection\pool.js:497:72
    at authenticateStragglers (C:\Users\super\AppData\Roaming\npm\node_modules\run-rs\node_modules\mongodb-topology-manager\node_modules\mongodb-core\lib\connection\pool.js:443:16)
    at Connection.messageHandler (C:\Users\super\AppData\Roaming\npm\node_modules\run-rs\node_modules\mongodb-topology-manager\node_modules\mongodb-core\lib\connection\pool.js:477:5)
    at Socket.<anonymous> (C:\Users\super\AppData\Roaming\npm\node_modules\run-rs\node_modules\mongodb-topology-manager\node_modules\mongodb-core\lib\connection\connection.js:333:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
```

**Comment by vkarpov15** [comment]
That's very strange, you shouldn't need any additional configs. Just plain old `run-rs` should work. What version of Windows?

**Comment by XHMM** [comment]
windows10😳

**Comment by chaiwa-berian** [comment]
@XHMM I have submitted a pull request for this issue #8. See pull request #15

**Comment by XHMM** [comment]
Solved !
